# Generated by Django 3.0.7 on 2020-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateField(default='YYYY-MM-DD')),
                ('registration_number', models.IntegerField(default=True, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('MobileNum', models.IntegerField(unique=True)),
                ('Password', models.CharField(default='NA', max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
    ]
